name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'fourthwave-api'
                  heroku_email: 'lbi213@nyu.edu'
              env:
                  HD_MONGO_DB: ${{secrets.MONGO_DB}}
                  HD_FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
                  HD_FIREBASE_PRIVATE_KEY: ${{secrets.FIREBASE_PRIVATE_KEY}}
                  HD_FIREBASE_CLIENT_EMAIL: ${{secrets.FIREBASE_CLIENT_EMAIL}}
